version: '3.7'

services:
  postgres:
    image: postgres:10.5-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8081

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - backend
    volumes:
      - ./frontend:/app
    command: npx vue-cli-service serve --port 3000 --mode development

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - postgres
      - backend
      - frontend

volumes:
  postgres_data:
